feat: 增加MySQL数据库支持
halo-sigs/charts pull request #5
Opened 2023-06-16 10:49 UTC by wan92hen

1. 增加 MySQL 数据库部署支持
2. 调整默认 Halo 镜像版本

2023-06-19 01:32 UTC, wan92hen commented
/hold

2023-06-19 07:44 UTC, wan92hen commented
```release-note
- 更新 Halo 版本到 v2.6.1
- 增加 MySQL 数据库部署支持
- 增加检测数据库连通性的初始化容器
```

2023-06-19 07:44 UTC, wan92hen commented
/unhold

2023-06-28 03:37 UTC, JohnNiang requested changes
Test steps:

```bash
gh repo clone halo-sigs/charts && cd charts
gh pr checkout 5
helm dependency build charts/halo
helm install halo -n halo charts/halo --create-namespace --set mysql.enabled=true --set postgresql.enabled=false
kubectl port-forward -n halo service/halo --address localhost 8090:http
```

Check the info of Halo:

```json
{
  "git": {
    "branch": "HEAD",
    "commit": {
      "id": "15433b5",
      "time": "2023-06-14T10:20:14Z"
    }
  },
  "build": {
    "artifact": "application",
    "name": "application",
    "time": "2023-06-14T10:33:11.814Z",
    "version": "2.6.1",
    "group": "run.halo.app"
  },
  "java": {
    "version": "17.0.7",
    "vendor": {
      "name": "Eclipse Adoptium",
      "version": "Temurin-17.0.7+7"
    },
    "runtime": {
      "name": "OpenJDK Runtime Environment",
      "version": "17.0.7+7"
    },
    "jvm": {
      "name": "OpenJDK 64-Bit Server VM",
      "vendor": "Eclipse Adoptium",
      "version": "17.0.7+7"
    }
  },
  "os": {
    "name": "Linux",
    "version": "5.15.49-linuxkit-pr",
    "arch": "aarch64"
  },
  "database": {
    "name": "Source distribution",
    "version": "8.0.33"
  }
}
```

It works very well, but I left some comments below, please take a look at them.

2023-06-28 03:37 UTC, JohnNiang commented on charts/halo/values.yaml
> +  enabled: false
建议恢复默认安装 postgresql 的配置。对于升级的用户，这里可能是一个破坏性更新。

2023-06-28 03:37 UTC, JohnNiang commented on charts/halo/values.yaml
> +  enabled: true
建议修改默认值为 false。默认还是安装 postgresql。

2023-06-28 03:49 UTC, wan92hen commented on charts/halo/values.yaml
> +  enabled: false
这里应该是测试的时候改了下忘记改回来了 :-(

2023-06-28 04:34 UTC, guqing reviewed
/lgtm

2023-06-28 06:59 UTC, JohnNiang approved these changes
/approve

2023-06-28 07:10 UTC, merged